version: "2"
services:
  varnish:
    image: herlon214/varnish
    ports:
    - "8011:6081"
    - "8082:6085"
    depends_on:
     - anon
    environment:
      BACKENDS: "anon"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
  anon:
    image: eeacms/hello
    environment:
      PORT: "8080"
